### PR TITLE
:sparkles: add safe area flag for custom options

### PR DESCRIPTION
**Pull request by vatsaltanna**

### CODE REVIEW

**Comment by MMMzq** [comment]
Thanks.

**Comment by vatsaltanna-simformsolutions** [comment]
@MMMzq , we are using this in one of the production app. so it will be very much helpful, if you can release the new version with this feature.

**Comment by vatsaltanna** [comment]
@MMMzq  we are using this in one of the production app. so it will be very much helpful, if you can release the new version with this feature.

**Comment by MMMzq** [comment]
I will release a new version soon.

**Comment by vatsaltanna** [comment]
Thanks

**Comment by MMMzq** [comment]
New version released

**Pull request merged**
